# Numpy

In [2]:
import numpy as np
import pandas as pd
from numpy import dtype

In [93]:
zeros_array = np.zeros((3, 4))
zeros_array
# np.ones((2, 3))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
# np.ones(15, dtype=bool).reshape(5, 3)
np.full(15, True, dtype=bool).reshape(5, 3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [113]:
# np.zeros(15, dtype=bool).reshape(5, 3)
# np.full(15, False, dtype=bool).reshape(5, 3)
~np.full(15, True, dtype=bool).reshape(5, 3)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [116]:
# np.arange(14)
# np.arange(0, 14, 2)
arr = np.arange(12).reshape(4, 3)
# arr = arr.reshape(-1)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
# np.sum(arr)
# np.sum(arr, axis=1)
# np.mean(arr)
# np.mean(arr, axis=1)
# np.mod(arr, 2)
# np.where(arr > 4, arr, 0)
# np.random.normal() # 정규분포 난수
np.random.normal(0, 1, 30) # 평균 0, 표준편차 1
# np.dot(np.arange(12).reshape(3, 4), arr)

array([-0.19330019,  0.88124547, -0.8707687 ,  0.81488346,  0.58645017,
       -0.55488937, -0.32322683, -0.12320271,  1.35406   ,  0.57612942,
       -1.73707828, -0.78038137, -0.41727292,  0.52887787, -1.66687497,
       -0.94241094,  0.42369966, -0.33425453, -0.41583465,  0.62863443,
        1.45376311,  0.97711017, -2.30115819, -0.02112213, -1.54907248,
        1.67597808, -0.9734414 ,  0.371848  ,  2.25211979,  1.37633686])

In [139]:
import numpy as np

# 행렬 곱셈을 einsum으로
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.einsum('ij,jk->ik', A, B)
print(result)
# 출력: [[19 22]
#        [43 50]]

# 복잡한 텐서 연산 - 배치 행렬 곱셈
batch_A = np.random.rand(3, 2, 2)
batch_B = np.random.rand(3, 2, 2)
batch_result = np.einsum('bij,bjk->bik', batch_A, batch_B)
# 배치 크기 3에서 각각 2x2 행렬곱 수행
print(f'\n\n---batch_A ---\n{batch_A}')
print(f'\n\n---batch_B ---\n{batch_B}')
print(f'\n\n---batch_result ---\n{batch_result}')

[[19 22]
 [43 50]]


---batch_A ---
[[[0.47223315 0.11948858]
  [0.25363371 0.41065016]]

 [[0.86241702 0.00349007]
  [0.29073748 0.71298443]]

 [[0.99711196 0.23620652]
  [0.9478744  0.47901527]]]


---batch_B ---
[[[0.00687013 0.36164277]
  [0.34973817 0.38229702]]

 [[0.10990699 0.80157972]
  [0.74597995 0.00791478]]

 [[0.33910927 0.82163832]
  [0.56101606 0.99955991]]]


---batch_result ---
[[[0.04503402 0.21645984]
  [0.14536253 0.24871513]]

 [[0.09738918 0.69132361]
  [0.56382617 0.23869238]]

 [[0.47064556 1.05536796]
  [0.59016825 1.25761439]]]


In [128]:
data = np.random.randint(1, 100, 30)

print(f"원본 데이터: {data}")

# False로 초기화된 마스크 생성
mask = np.zeros(30, dtype=bool)
print(mask)
# 조건에 따라 마스크 업데이트
mask[data > 50] = True  # 50보다 큰 값들만 True로 변경

print(f'\n\n{mask}')

원본 데이터: [54 55 83 56 75 22 61 80 64 84 31 92 58 73 71 71  3 53 41 66 24 27 11 15
 10 51 40 58 18 51]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]


[ True  True  True  True  True False  True  True  True  True False  True
  True  True  True  True False  True False  True False False False False
 False  True False  True False  True]


# Pandas

In [89]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'salary': [50000, 60000, 70000]
}
df = pd.DataFrame(data)
print(f'{df.info()}\n\n{df.describe()}\n\n{df.head(2)}\n\n{df.tail(1)}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
 2   salary  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

        age   salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

    name  age  salary
0  Alice   25   50000
1    Bob   30   60000

      name  age  salary
2  Charlie   35   70000


In [117]:
# 7. 컬럼 선택
ages = df['age']  # 단일 컬럼
subset = df[['name', 'age']]  # 복수 컬럼

# 8. 인덱싱
row_data = df.loc[0]  # 라벨 기반
cell_value = df.iloc[0, 1]  # 위치 기반

# 9. apply() - 사용자 정의 함수 적용
df['age_category'] = df['age'].apply(lambda x: 'Young' if x < 30 else 'Senior')

# 10. merge() - 데이터 병합
# merged = pd.merge(df1, df2, on='key_column')
df

name  age  salary age_category
0    Alice   25   50000        Young
1      Bob   30   60000       Senior
2  Charlie   35   70000       Senior

In [119]:
df

NameError: name 'age' is not defined

In [79]:
series = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
series

a    10
b    20
c    30
d    40
dtype: int64

name  age  salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000